# Generated by Django 3.2.25 on 2025-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
    ]
