# Generated by Django 3.2.25 on 2025-07-23 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_supply_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='quantity_available',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
