# Generated by Django 3.2.25 on 2025-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_supply_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
